# Site settings
title: David Stephens
email: d@davidstephens.uk
description: 'Technologist living in London.'
baseurl: ""
url: "http://davidstephens.uk"

# Build settings
markdown: kramdown
permalink: pretty

paginate:         5

