# Site settings
title: David Stephens
tagline: 'British technologist living in London.'
email: dave@davidstephens.uk
description: 'Personal site of David Stephens, a British technologist living in London.'
baseurl: ""
url: "http://davidstephens.uk"

author:
  name: 'David Stephens'
  url: https://github.com/DaveStephens

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5

plugins:
  - jekyll-sitemap
  - jekyll-paginate

